export const KUWAIT_AREAS: { nameAr: string; id: number; govId: number }[] = [
  {nameAr:"الخالدية",id:57,govId:1},{nameAr:"الدسمة",id:62,govId:1},{nameAr:"الدعية",id:63,govId:1},{nameAr:"الدوحة",id:64,govId:1},{nameAr:"الروضة",id:10,govId:1},{nameAr:"السرة",id:47,govId:1},{nameAr:"الشامية",id:8,govId:1},{nameAr:"الشرق",id:48,govId:1},{nameAr:"الشويخ السكنية",id:45,govId:1},{nameAr:"الشويخ الصناعية",id:49,govId:1},{nameAr:"الصليبيخات",id:60,govId:1},{nameAr:"العديلية",id:55,govId:1},{nameAr:"الفيحاء",id:51,govId:1},{nameAr:"القادسية",id:53,govId:1},{nameAr:"القبلة",id:5,govId:1},{nameAr:"القيروان",id:61,govId:1},{nameAr:"المباركية",id:66,govId:1},{nameAr:"المرقاب",id:2,govId:1},{nameAr:"المنصورية",id:7,govId:1},{nameAr:"النزهة",id:58,govId:1},{nameAr:"اليرموك",id:65,govId:1},{nameAr:"بنيد القار",id:4,govId:1},{nameAr:"جابر الأحمد",id:46,govId:1},{nameAr:"حصة المبارك",id:59,govId:1},{nameAr:"دسمان",id:3,govId:1},{nameAr:"شمال غرب الصليبيخات",id:50,govId:1},{nameAr:"عبدالله السالم",id:56,govId:1},{nameAr:"غرناطة",id:52,govId:1},{nameAr:"قرطبة",id:54,govId:1},{nameAr:"كيفان",id:9,govId:1},
  {nameAr:"البدع",id:75,govId:2},{nameAr:"الجابرية",id:17,govId:2},{nameAr:"الرميثية",id:12,govId:2},{nameAr:"الزهراء",id:68,govId:2},{nameAr:"السالمية",id:16,govId:2},{nameAr:"السلام",id:67,govId:2},{nameAr:"الشعب البحري",id:74,govId:2},{nameAr:"الشعب السكني",id:71,govId:2},{nameAr:"الشهداء",id:70,govId:2},{nameAr:"الصديق",id:69,govId:2},{nameAr:"بيان",id:14,govId:2},{nameAr:"حطين",id:20,govId:2},{nameAr:"حولي",id:11,govId:2},{nameAr:"سلوى",id:13,govId:2},{nameAr:"مبارك العبدالله",id:72,govId:2},{nameAr:"مشرف",id:15,govId:2},{nameAr:"ميدان حولي",id:73,govId:2},
  {nameAr:"اسطبلات الفروانية",id:90,govId:3},{nameAr:"اشبيلية",id:83,govId:3},{nameAr:"الاندلس",id:79,govId:3},{nameAr:"الرابية",id:87,govId:3},{nameAr:"الرحاب",id:23,govId:3},{nameAr:"الرقعي",id:24,govId:3},{nameAr:"الري",id:81,govId:3},{nameAr:"الضجيج",id:88,govId:3},{nameAr:"العارضية",id:80,govId:3},{nameAr:"العارضية الحرفية",id:84,govId:3},{nameAr:"العمرية",id:26,govId:3},{nameAr:"الفردوس",id:89,govId:3},{nameAr:"الفروانية",id:21,govId:3},{nameAr:"جليب الشيوخ",id:85,govId:3},{nameAr:"جنوب عبدالله المبارك",id:77,govId:3},{nameAr:"خيطان",id:22,govId:3},{nameAr:"خيطان الجنوبي الجديدة",id:78,govId:3},{nameAr:"صباح الناصر",id:86,govId:3},{nameAr:"عبدالله المبارك",id:82,govId:3},{nameAr:"غرب عبدالله المبارك",id:76,govId:3},
  {nameAr:"ابو الحصانية",id:95,govId:4},{nameAr:"ابو فطيرة",id:91,govId:4},{nameAr:"العدان",id:93,govId:4},{nameAr:"الفنيطيس",id:29,govId:4},{nameAr:"القرين",id:96,govId:4},{nameAr:"القصور",id:94,govId:4},{nameAr:"المسائل",id:92,govId:4},{nameAr:"المسيلة",id:32,govId:4},{nameAr:"صباح السالم",id:30,govId:4},{nameAr:"صبحان",id:98,govId:4},{nameAr:"غرب ابو فطيرة الحرفية",id:97,govId:4},{nameAr:"مبارك الكبير",id:28,govId:4},
  {nameAr:"ابو حليفة",id:118,govId:5},{nameAr:"اسطبلات الاحمدي",id:110,govId:5},{nameAr:"الاحمدي",id:117,govId:5},{nameAr:"الجليعة",id:102,govId:5},{nameAr:"الخيران السكنية",id:100,govId:5},{nameAr:"الرقة",id:39,govId:5},{nameAr:"الزور",id:103,govId:5},{nameAr:"الشعيبة الصناعية",id:106,govId:5},{nameAr:"الصباحية",id:113,govId:5},{nameAr:"الضباعية",id:108,govId:5},{nameAr:"الظهر",id:101,govId:5},{nameAr:"العقيلة",id:112,govId:5},{nameAr:"الفحيحيل",id:34,govId:5},{nameAr:"الفنطاس",id:38,govId:5},{nameAr:"المنقف",id:35,govId:5},{nameAr:"المهبولة",id:36,govId:5},{nameAr:"النويصيب",id:104,govId:5},{nameAr:"الوفرة",id:121,govId:5},{nameAr:"الوفرة السكنية",id:115,govId:5},{nameAr:"بنيدر",id:105,govId:5},{nameAr:"جابر العلي",id:99,govId:5},{nameAr:"جنوب صباح الاحمد",id:109,govId:5},{nameAr:"صباح الاحمد البحرية",id:114,govId:5},{nameAr:"صباح الاحمد السكنية",id:111,govId:5},{nameAr:"علي صباح السالم",id:119,govId:5},{nameAr:"فهد الاحمد",id:116,govId:5},{nameAr:"ميناء عبدالله",id:107,govId:5},{nameAr:"هدية",id:120,govId:5},
  {nameAr:"اسطبلات الجهراء",id:133,govId:6},{nameAr:"الجهراء الصناعية",id:134,govId:6},{nameAr:"الجهراء القديمة",id:124,govId:6},{nameAr:"الخويسات",id:137,govId:6},{nameAr:"الصبية",id:132,govId:6},{nameAr:"الصليبية",id:129,govId:6},{nameAr:"الصليبيخات",id:41,govId:6},{nameAr:"العبدلي",id:130,govId:6},{nameAr:"العيون",id:127,govId:6},{nameAr:"القصر",id:43,govId:6},{nameAr:"المطلاع",id:122,govId:6},{nameAr:"النسيم",id:123,govId:6},{nameAr:"النعايم",id:138,govId:6},{nameAr:"النعيم",id:42,govId:6},{nameAr:"النهضة",id:139,govId:6},{nameAr:"الهجن",id:128,govId:6},{nameAr:"الواحة",id:125,govId:6},{nameAr:"امغرة الصناعية",id:126,govId:6},{nameAr:"تيماء",id:136,govId:6},{nameAr:"جنوب سعد العبدالله",id:135,govId:6},{nameAr:"سعد العبدالله",id:44,govId:6},{nameAr:"كبد",id:131,govId:6},
];

export function getAreasByGovId(govId: number): { nameAr: string; id: number; govId: number }[] {
  return KUWAIT_AREAS.filter(a => a.govId === govId);
}
