import nodemailer from "nodemailer";
import { logger } from "./logger";

type SendOfficeOtpInput = {
  to: string;
  name: string;
  otp: string;
};

type SendOfficePasswordResetInput = {
  to: string;
  name: string;
  resetUrl: string;
};

type SendSupportTicketInput = {
  officeName: string;
  officePhone?: string | null;
  officeWhatsapp?: string | null;
  officeEmail?: string | null;
  type: string;      // استفسار | اقتراح
  section: string;   // القسم المتعلّق
  message: string;
};

// Inbox that receives office support tickets. Forwards to the team (Gmail).
const SUPPORT_INBOX = process.env.SUPPORT_EMAIL || "support@finde.co";

function smtpConfigured(): boolean {
  return Boolean(process.env.SMTP_HOST && (process.env.SMTP_FROM || process.env.SMTP_USER));
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/** Shared card shell so every Finde email looks the same. */
function shell(bodyHtml: string, footer?: string): string {
  const foot = footer ?? "هذه رسالة آلية من نظام Finde، وهذا البريد لا يستقبل الردود — من فضلك لا ترد عليها.";
  return `
    <div dir="rtl" style="margin:0;padding:0;background:#F6F8FC;font-family:Arial,Tahoma,sans-serif;color:#111827">
      <div style="width:100%;max-width:520px;margin:0 auto;padding:22px 14px;box-sizing:border-box">
        <div style="background:#FFFFFF;border:1px solid #E6EAF1;border-radius:16px;padding:22px 18px;text-align:right;box-shadow:0 10px 28px rgba(15,23,42,0.08)">
          ${bodyHtml}
          <div style="font-size:12px;line-height:1.8;color:#94A3B8;margin-top:8px;border-top:1px solid #EEF2F7;padding-top:10px">${foot}</div>
        </div>
      </div>
    </div>
  `;
}

async function send(input: {
  to: string;
  subject: string;
  text: string;
  html: string;
  label: string;
  replyTo?: string;
  // Most Finde mail is an automated notification to a user; those get the
  // auto-generated headers. A support ticket is the opposite — a human on the
  // team is meant to read and reply — so callers can opt out.
  autoGenerated?: boolean;
}): Promise<boolean> {
  const port = Number(process.env.SMTP_PORT || 587);
  const secure = process.env.SMTP_SECURE === "true" || port === 465;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port,
    secure,
    auth: user || pass ? { user, pass } : undefined,
  });

  const autoGenerated = input.autoGenerated !== false;
  try {
    await transporter.sendMail({
      from: process.env.SMTP_FROM || user,
      to: input.to,
      ...(input.replyTo ? { replyTo: input.replyTo } : {}),
      subject: input.subject,
      text: input.text,
      html: input.html,
      // Automated, unmonitored mailbox — signal to mail clients / auto-responders.
      ...(autoGenerated
        ? { headers: { "Auto-Submitted": "auto-generated", "X-Auto-Response-Suppress": "All" } }
        : {}),
    });
    return true;
  } catch (err) {
    logger.error({ err, to: input.to }, `Failed to send ${input.label}`);
    return false;
  }
}

export async function sendOfficeVerificationOtp(input: SendOfficeOtpInput): Promise<boolean> {
  if (!smtpConfigured()) {
    if (process.env.NODE_ENV !== "production") {
      logger.warn({ to: input.to, otp: input.otp }, "SMTP not configured; office verification OTP logged for development");
      return true;
    }
    logger.error("SMTP is not configured; cannot send office verification OTP");
    return false;
  }

  const safeName = escapeHtml(input.name);
  return send({
    to: input.to,
    label: "office verification OTP",
    subject: "رمز تفعيل حسابك في Finde",
    text: `مرحباً ${input.name}\n\nرمز تفعيل حسابك هو: ${input.otp}\n\nالرمز صالح لمدة 10 دقائق.\n\nهذه رسالة آلية من نظام Finde، وهذا البريد لا يستقبل الردود — من فضلك لا ترد عليها.`,
    html: shell(`
      <div style="font-size:20px;font-weight:800;margin:0 0 10px;color:#111827">تفعيل حسابك في Finde</div>
      <div style="font-size:15px;line-height:1.8;margin:0 0 14px;color:#334155">مرحباً ${safeName}</div>
      <div style="font-size:15px;line-height:1.8;margin:0 0 14px;color:#334155">استخدم الرمز التالي لتفعيل بريدك الإلكتروني:</div>
      <div dir="ltr" style="display:block;width:100%;box-sizing:border-box;background:#EEF2FF;border:1px solid #C7D2FE;border-radius:14px;padding:16px 8px;text-align:center;font-size:30px;font-weight:800;letter-spacing:7px;color:#4B66E0;margin:16px 0">${input.otp}</div>
      <div style="font-size:13px;line-height:1.8;color:#64748B">الرمز صالح لمدة 10 دقائق. إذا لم تطلب إنشاء حساب، يمكنك تجاهل هذه الرسالة.</div>
    `),
  });
}

export async function sendSupportTicket(input: SendSupportTicketInput): Promise<boolean> {
  if (!smtpConfigured()) {
    if (process.env.NODE_ENV !== "production") {
      logger.warn({ ...input }, "SMTP not configured; support ticket logged for development");
      return true;
    }
    logger.error("SMTP is not configured; cannot deliver support ticket");
    return false;
  }

  const name = escapeHtml(input.officeName);
  const type = escapeHtml(input.type);
  const section = escapeHtml(input.section);
  const phone = input.officePhone ? escapeHtml(input.officePhone) : "—";
  const whatsapp = input.officeWhatsapp ? escapeHtml(input.officeWhatsapp) : "—";
  const email = input.officeEmail ? escapeHtml(input.officeEmail) : "—";
  const message = escapeHtml(input.message).replace(/\n/g, "<br>");

  const row = (label: string, value: string) => `
    <tr>
      <td style="padding:6px 10px;font-size:13px;color:#64748B;white-space:nowrap;vertical-align:top">${label}</td>
      <td style="padding:6px 10px;font-size:14px;font-weight:700;color:#111827">${value}</td>
    </tr>`;

  return send({
    to: SUPPORT_INBOX,
    label: "office support ticket",
    replyTo: input.officeEmail || undefined,
    autoGenerated: false, // a human on the team should read and reply
    subject: `[${input.type} · ${input.section}] رسالة من ${input.officeName}`,
    text:
      `رسالة دعم جديدة من مكتب على Finde\n\n` +
      `النوع: ${input.type}\nالقسم: ${input.section}\n\n` +
      `المكتب: ${input.officeName}\nالبريد: ${input.officeEmail || "—"}\n` +
      `الهاتف: ${input.officePhone || "—"}\nواتساب: ${input.officeWhatsapp || "—"}\n\n` +
      `الرسالة:\n${input.message}`,
    html: shell(`
      <div style="font-size:20px;font-weight:800;margin:0 0 4px;color:#111827">رسالة دعم جديدة</div>
      <div style="margin:0 0 14px">
        <span style="display:inline-block;font-size:12px;font-weight:800;color:#4B66E0;background:#EEF2FF;border:1px solid #C7D2FE;border-radius:999px;padding:3px 12px;margin-inline-end:6px">${type}</span>
        <span style="display:inline-block;font-size:12px;font-weight:800;color:#0F766E;background:#ECFDF5;border:1px solid #A7F3D0;border-radius:999px;padding:3px 12px">${section}</span>
      </div>
      <table style="width:100%;border-collapse:collapse;background:#F8FAFC;border:1px solid #EEF2F7;border-radius:12px;overflow:hidden;margin:0 0 14px">
        ${row("المكتب", name)}
        ${row("البريد", `<span dir="ltr">${email}</span>`)}
        ${row("الهاتف", `<span dir="ltr">${phone}</span>`)}
        ${row("واتساب", `<span dir="ltr">${whatsapp}</span>`)}
      </table>
      <div style="font-size:13px;color:#64748B;margin:0 0 6px">نص الرسالة:</div>
      <div style="font-size:15px;line-height:1.9;color:#1F2937;background:#fff;border:1px solid #E6EAF1;border-radius:12px;padding:14px 16px">${message}</div>
    `, `يمكنك الرد على هذه الرسالة مباشرةً للتواصل مع المكتب${input.officeEmail ? ` (${email})` : ""}.`),
  });
}

export async function sendOfficePasswordReset(input: SendOfficePasswordResetInput): Promise<boolean> {
  if (!smtpConfigured()) {
    if (process.env.NODE_ENV !== "production") {
      logger.warn({ to: input.to, resetUrl: input.resetUrl }, "SMTP not configured; password reset link logged for development");
      return true;
    }
    logger.error("SMTP is not configured; cannot send password reset link");
    return false;
  }

  const safeName = escapeHtml(input.name);
  const safeUrl = escapeHtml(input.resetUrl);
  return send({
    to: input.to,
    label: "office password reset",
    subject: "إعادة تعيين كلمة المرور في Finde",
    text: `مرحباً ${input.name}\n\nلإعادة تعيين كلمة المرور الخاصة بحسابك في Finde، افتح الرابط التالي:\n${input.resetUrl}\n\nالرابط صالح لمدة 60 دقيقة ويُستخدم مرة واحدة.\nإذا لم تطلب إعادة التعيين، تجاهل هذه الرسالة وكلمة مرورك ستبقى كما هي.\n\nهذه رسالة آلية من نظام Finde، وهذا البريد لا يستقبل الردود — من فضلك لا ترد عليها.`,
    html: shell(`
      <div style="font-size:20px;font-weight:800;margin:0 0 10px;color:#111827">إعادة تعيين كلمة المرور</div>
      <div style="font-size:15px;line-height:1.8;margin:0 0 14px;color:#334155">مرحباً ${safeName}</div>
      <div style="font-size:15px;line-height:1.8;margin:0 0 18px;color:#334155">وصلنا طلب لإعادة تعيين كلمة المرور الخاصة بحسابك في Finde. اضغط الزر التالي لاختيار كلمة مرور جديدة:</div>
      <div style="text-align:center;margin:0 0 18px">
        <a href="${safeUrl}" style="display:inline-block;background:#667EEA;color:#FFFFFF;text-decoration:none;font-size:16px;font-weight:800;padding:14px 34px;border-radius:12px">تعيين كلمة مرور جديدة</a>
      </div>
      <div dir="ltr" style="font-size:12px;line-height:1.7;color:#94A3B8;word-break:break-all;background:#F8FAFC;border:1px solid #EEF2F7;border-radius:10px;padding:10px;margin:0 0 14px">${safeUrl}</div>
      <div style="font-size:13px;line-height:1.8;color:#64748B">الرابط صالح لمدة 60 دقيقة ويُستخدم مرة واحدة. إذا لم تطلب إعادة التعيين، تجاهل هذه الرسالة وكلمة مرورك ستبقى كما هي.</div>
    `),
  });
}
